services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PYSPARK_PYTHON=python
    # expose ports only when you run Streamlit from this service
    ports:
      - "8501:8501"
