services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    init: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app     # so 'src' imports work when Streamlit runs from /app/app
    command: bash -lc "streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    # If Spark misbehaves on Apple Silicon, you may force x86:
    # platform: linux/amd64
