version: "3.9"

services:
  airflow-webserver:
    image: local/airflow-dockercli:2.9.3
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      PYTHONPATH: "/opt/airflow:/opt/airflow/repo:/opt/airflow/repo/src"
      REPO_DIR: "/opt/airflow/repo"
    user: "0:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - .:/opt/airflow/repo
      - /var/run/docker.sock:/var/run/docker.sock
      - airflow_home:/opt/airflow

  airflow-scheduler:
    image: local/airflow-dockercli:2.9.3
    command: scheduler
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCH_
