# ruff.toml (single file, single [lint] table)

line-length = 100
target-version = "py310"

# Optional: keep noise out of the linter
extend-exclude = ["data", "models", "logs", ".venv", ".airflow_venv"]

[lint]
# Core rules: pycodestyle (E/W), pyflakes (F), isort (I), pyupgrade (UP)
select = ["E", "F", "I", "UP"]

# Black compatibility & common false-positives
ignore = ["E203", "W503"]

[lint.isort]
combine-as-imports = true
known-first-party = ["src", "app", "airflow"]

[lint.per-file-ignores]
# Airflow drops a long single line in this generated file; don't fail the build for it
"airflow/webserver_config.py" = ["E501"]
