# ruff.toml (single file)

line-length = 100
target-version = "py310"
extend-exclude = ["data", "models", "logs", ".venv", ".airflow_venv"]

[lint]
# Core rule sets: pycodestyle (E), pyflakes (F), isort (I), pyupgrade (UP)
select = ["E", "F", "I", "UP"]

# Black-compat & typical noise
ignore = ["E203"]  # (Removed W503 to avoid the 'Unknown rule selector' error)

[lint.isort]
combine-as-imports = true
known-first-party = ["src", "app", "airflow"]

[lint.per-file-ignores]
# Airflow drops a long single line in this generated file; don't fail the build for it
"airflow/webserver_config.py" = ["E501"]
